pipeline:
  install:
    image: node:${NODE_TAG_VERSION}
    pull: true
    commands:
     - npm ci

  lint:
    group: lint-and-test
    image: node:${NODE_TAG_VERSION}
    commands:
     - npm run lint

  test:
    group: lint-and-test
    image: node:${NODE_TAG_VERSION}
    commands:
     - npm test

  publish:
    when:
      tag: release*
      event: tag
      branch: main
      status: success
    image: node:current-alpine
    commands:
      - npm config set //registry.npmjs.org/:_authToken=$${NPM_TOKEN}
      - npm publish

branches: main

matrix:
  NODE_TAG_VERSION:
    - erbium-alpine
    - lts-alpine
    - current-alpine
